### ISSUE TITLE
求更新使用说明，求能上百度

### ISSUE THREAD

**Issue by code4lala** [Yesterday17/jlu-http-proxy#1]
`go build`之后出现`jlu-http-proxy.exe`
我瞎蒙的配置文件`config.json`
``` json
{
	"username" : "我的用户名",
	"password" : "我的密码",
	"port" : "2116",

	"directory": ".",
	"mark": 0,
	"http2": false,
	"auto_reauth": false,
	"cookies" : ""
}
```

执行输出如下：
```
>jlu-http-proxy.exe
Start server on port 2116
2020/03/05 09:24:33 Server Handshake: remote error: tls: unknown certificate
2020/03/05 09:24:37 Server Handshake: remote error: tls: unknown certificate
后边一直重复上一行
```
能上uims，不能上百度
![Snipaste_2020-03-05_09-28-11](https://user-images.githubusercontent.com/24974976/75938881-cb42ae80-5ec3-11ea-9e60-554e910f5a09.png)

PS: 登上vpns.jlu.edu.cn之后直接打开 https://vpns.jlu.edu.cn/https/77726476706e69737468656265737421e7e056d2253161546b468aa395/ 就是校园网的百度，不知道对你有么有帮助

感谢作者的努力工作，催更！

**Comment by Yesterday17** [comment]
CA导入了吗（
它会在 `directory` 的目录内生成CA，之后用 `CA` 对 `https` 网站进行自签名，所以浏览器导入CA就正常了。
Server handshake 这个有点奇怪，本质原因是 vpns 用的证书是有问题的，但我应该已经忽略证书错误了，不知道为什么还有提示。
总之你先试试导入CA(?)

**Comment by code4lala** [comment]
好使了！导入CA之后就一切正常了！
导入证书找的教程：https://docs.vmware.com/cn/Horizon-FLEX/1.12/com.vmware.horizon.flex.admin.doc/GUID-AEB47CE4-FECB-49B2-ABA0-AD4BE6D9267A.html

**Comment by code4lala** [comment]
![导入证书后](https://user-images.githubusercontent.com/24974976/76044590-c5b59900-5f95-11ea-8685-d85ff9307550.png)
谢谢dalao！

**Comment by Yesterday17** [comment]
我之后完善一下 Readme 吧（
