### ISSUE TITLE
自动登录问题

### ISSUE THREAD

**Issue by icespite** [Yesterday17/jlu-http-proxy#3]
自动登录（每次登录时的第一次使用）会加载不出来vpns的重定向，需要重新进网站。

**Comment by icespite** [comment]
![image](https://user-images.githubusercontent.com/50160905/87767992-0d0a3b00-c84e-11ea-84a1-33a70f5f0200.png)

**Comment by icespite** [comment]
![image](https://user-images.githubusercontent.com/50160905/87768021-185d6680-c84e-11ea-9995-6b4185d59b8b.png)

**Comment by Yesterday17** [comment]
（刷新这个页面呢

**Comment by icespite** [comment]
无效
